-- Add missing columns to the songs table
ALTER TABLE songs ADD COLUMN IF NOT EXISTS url VARCHAR(512);
ALTER TABLE songs ADD COLUMN IF NOT EXISTS youtube_id VARCHAR(30);
ALTER TABLE songs ADD COLUMN IF NOT EXISTS source VARCHAR(50);

-- Add any missing created_at and updated_at columns
ALTER TABLE songs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 